// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-_hEdU9fphS1XyO7PwRIZgPS1oCOMdTY',
    appId: '1:365056796826:web:ccc15491d355d1ed259723',
    messagingSenderId: '365056796826',
    projectId: 'drywall-9455e',
    authDomain: 'drywall-9455e.firebaseapp.com',
    storageBucket: 'drywall-9455e.appspot.com',
    measurementId: 'G-JWWRXN35BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzLx9OsTEhyqxjoLTb39Ks6AIU0AvI0Cc',
    appId: '1:365056796826:android:e2d46290bbc2be01259723',
    messagingSenderId: '365056796826',
    projectId: 'drywall-9455e',
    storageBucket: 'drywall-9455e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzlDPyQfTImaQXstMWwwLBWSUjV3d3tcY',
    appId: '1:365056796826:ios:653000244e59b30b259723',
    messagingSenderId: '365056796826',
    projectId: 'drywall-9455e',
    storageBucket: 'drywall-9455e.appspot.com',
    iosClientId: '365056796826-j00q4pr2v3uje4jdhs5vvld8pidhp3cj.apps.googleusercontent.com',
    iosBundleId: 'com.example.drivel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzlDPyQfTImaQXstMWwwLBWSUjV3d3tcY',
    appId: '1:365056796826:ios:653000244e59b30b259723',
    messagingSenderId: '365056796826',
    projectId: 'drywall-9455e',
    storageBucket: 'drywall-9455e.appspot.com',
    iosClientId: '365056796826-j00q4pr2v3uje4jdhs5vvld8pidhp3cj.apps.googleusercontent.com',
    iosBundleId: 'com.example.drivel',
  );
}
